language: node_js
node_js:
- "node"
cache: npm
script:
- npm run lint
- npm run test:ci 
- npm run deploy
after_script: npm run alias
env:
  global:
    secure: QbE5rt/QAW5SwnNad3sX5saNfeL9ln2t7aQopQaFDO/uGS6aIIDoIQqwzVTZUzxOCEOYYbZ/P+iMnFmurrib1YhkD7OflRQ6HJZpMHNDXRUb5XNfifdD0LgHNE2O2PfmuPlHh1iMRtlKnLuplBEGn8DszlSrEtqvpjhWsVvXJLTTM6kgBP8jT0rW2SCbURc0RjXxDHuA+0XleroEgmk3TsSpGc3I4lOPYPuj0RITg2QfoorGgkJKeWd7NzLmpcz2VECq4ygjl+fjAyctYEIZCQetsxm9Px/SZJtlV5l4a6AUxhtgFv+G4Z7dtb4h+WAG41W/fDF5Sq7ZaNnZZhJZqhNBeCsVZfIQ1AQ5rLJlOynoo3OL8pd4/rfUZ25j0BY04nScwnY1GiI3j0kys83cbpLbo7f1aqWurYQUB9wDHHEeh/tvF/F2DL4AvjEIqRIA4WJp7uEue2ejl7rGEKvSxhu9Gz1+XjJjXly6uCZL/6oYuQBP9ZNTuRNHkT2UY3embcUbFzwkk3MPy3Lr5KsEJondFgWL50WODyCZvCOX61+YRQN1974xdXDyfDk9lTiBw/HKh45BKHrnVmdq+ksfs/Ras5mBBD4Q2Ij1LkhTX/ngTAZc9zKz5h9gzpJPxJcQIsVwPKEuHqN1uAgCmMzBIJgacZKVN0miVVREjR9oG7k=
